INSERT IGNORE INTO Student_G00387819.heroes (id,name,gender,race,eye_colour,hair_colour,full_name,alter_egos,place_of_birth,alignment,occupation)
VALUES
    (1,"A-Bomb","Male","Human","Yellow","No Hair","Richard Milhouse Jones",null,"Scarsdale, Arizona","good","Musician, adventurer, author; formerly talk show host"),
    (2,"Abe Sapien","Male","Icthyo Sapien","Blue","No Hair","Abraham Sapien",null,"-","good","Paranormal Investigator"),
    (3,"Abin Sur","Male","Ungaran","Blue","No Hair",null,null,"Ungara","good","Green Lantern, former history professor"),
    (4,"Abomination","Male","Human / Radiation","Green","No Hair","Emil Blonsky",null,"Zagreb, Yugoslavia","bad","Ex-Spy"),
    (5,"Abraxas","Male","Cosmic Entity","Blue","Black","Abraxas",null,"Within Eternity","bad","Dimensional destroyer"),
    (6,"Absorbing Man","Male","Human","Blue","No Hair","Carl Creel",null,"New York City, New York","bad","Professional criminal; former professional boxer"),
    (7,"Adam Monroe","Male",null,"Blue","Blond",null,null,"-","good","former samurai swordsman, former British mercenary commander, former soldier in the Confederate Army"),
    (8,"Adam Strange","Male","Human","Blue","Blond","Adam Strange",null,"Chicago, Illinois","good","Adventurer, archaelogist, ambassador"),
    (10,"Agent Bob","Male","Human","Brown","Brown","Bob",null,"-","good","Mercenary, janitor; former pirate, terrorist"),
    (11,"Agent Zero","Male",null,"-","-","Christoph Nord",null,"Unrevealed location in former East Germany","good","Mercenary, former government operative, freedom fighter"),
    (12,"Air-Walker","Male",null,"Blue","White","Gabriel Lan",null,"Xandar, a planet in the Tranta system, Andromeda galaxy","bad","Former starship captain, Herald of Galactus"),
    (13,"Ajax","Male","Cyborg","Brown","Black","Francis",null,"-","bad","-"),
    (14,"Alan Scott","Male",null,"Blue","Blond","Alan Ladd Wellington Scott",null,"Gotham City","good","-"),
    (15,"Alex Mercer","Male","Human","-","-","Alexander J. Mercer",null,"-","bad","-"),
    (17,"Alfred Pennyworth","Male","Human","Blue","Black","Alfred Thaddeus Crane Pennyworth",null,"-","good","Butler; Caretaker, former Actor; Field Medic; Government Agent"),
    (18,"Alien","Male","Xenomorph XX121","-","No Hair","Xenomorph",null,"Your chest :)","bad","-"),
    (20,"Amazo","Male","Android","Red","-",null,null,"-","bad","-"),
    (23,"Angel","Male","Vampire","-","-","Liam",null,"-","good","-"),
    (24,"Angel","Male",null,"Blue","Blond","Warren Kenneth Worthington III",null,"Centerport, Long Island, New York","good","Adventurer, chairman & principal stockholder of Worthington Industries, former terrorist"),
    (25,"Angel Dust","Female","Mutant","Yellow","Black","Christina",null,"-","good","-"),
    (26,"Angel Salvadore","Female",null,"Brown","Black","Angel Salvadore Bohusk",null,"-","good","-"),
    (28,"Animal Man","Male","Human","Blue","Blond","Bernhard Baker",null,"-","good","-"),
    (29,"Annihilus","Male",null,"Green","No Hair","Annihilus",null,"Planet of Arthros, Sector 17A, Negative Zone","bad","Conqueror, scavenger"),
    (30,"Ant-Man","Male","Human","Blue","Blond","Hank Pym",null,"Elmsford, New York","good","Adventurer, Biochemist, former manager of Avengers Compound"),
    (31,"Ant-Man II","Male","Human","Blue","Blond","Scott Lang",null,"Coral Gables, Florida","good","Electronics Technician,"),
    (32,"Anti-Monitor","Male","God / Eternal","Yellow","No Hair",null,null,"Moon of Qward","bad","-"),
    (34,"Anti-Venom","Male","Symbiote","Blue","Blond","Eddie Brock",null,"San Francisco, California","-","Vigilante; former journalist for the Daily Globe"),
    (35,"Apocalypse","Male","Mutant","Red","Black","En Sabah Nur",null,"Akkaba, Egypt","bad","Student; formerly Conqueror; Scientist"),
    (36,"Aquababy","Male",null,"Blue","Blond","Arthur Curry, Jr.",null,"-","good","-"),
    (37,"Aqualad","Male","Atlantean","Blue","Black","Garth",null,"Poseidonis, Atlantis","good","Adventurer; Magician, former Sidekick"),
    (38,"Aquaman","Male","Atlantean","Blue","Blond","Orin",null,"Atlantis","good","Protector of the Seas and Oceans, King of Poseidonis"),
    (39,"Arachne","Female","Human","Blue","Blond","Julia Carpenter",null,"Los Angeles, California","good","Adventurer, fugitive, former government agent"),
    (40,"Archangel","Male","Mutant","Blue","Blond","Warren Kenneth Worthington III",null,"Centerport, Long Island, New York","good","Adventurer, Chairman & principal stockholder of Worthington Industries, Multi-Millionaire, Heir, former terrorist"),
    (41,"Arclight","Female",null,"Violet","Purple","Philippa Sontag",null,"Vietnam","bad","Terrorist"),
    (42,"Ardina","Female","Alien","White","Orange","Ardina",null,"-","good","-"),
    (43,"Ares","Male",null,"Brown","Brown",null,null,"-","good","-"),
    (44,"Ariel","Female",null,"Purple","Pink","Ariel",null,"-","good","Leader, refugee alien; former alien mutant-hunter and hedonist"),
    (45,"Armor","Female",null,"Black","Black","Hisako Ichiki",null,"-","good","Adventurer, student"),
    (48,"Atlas","Male","Mutant","Brown","Red","Erik Josten",null,"Milwaukee, Wisconsin","good","Adventurer; former professional criminal, mercenary, dock worker, soldier"),
    (49,"Atlas","Male","God / Eternal","Blue","Brown",null,null,"Crystal Mountain","bad","-"),
    (52,"Atom Girl","Female",null,"Black","Black","Salu Digby",null,"-","good","-"),
    (53,"Atom II","Male","Human","Brown","Auburn","Ray Palmer",null,"-","good","Physics Professor"),
    (56,"Aurora","Female","Mutant","Blue","Black","Jeanne-Marie Beaubier",null,"Montreal, Quebec, Canada","good","Adventurer; former terrorist, nun, history/geography teacher"),
    (57,"Azazel","Male","Neyaphem","Yellow","Black",null,null,"Isla des Demonas, Caribbean Sea","bad","Leader of the Neyaphem"),
    (58,"Azrael","Male","Human","Brown","Black","Michael Washington Lane",null,"Gotham City","good","Former Police Officer, vigilante"),
    (60,"Bane","Male","Human","-","-",null,null,"-","bad","-"),
    (61,"Banshee","Male","Human","Green","Strawberry Blond","Sean Cassidy",null,"Cassidy Keep, Ireland","good","Currently founder and director of operation for X-Corps, formerly Adventurer and Headmaster at the Massachusetts Academy, in charge of Generation X, Interpol Inspector and Agent, freelance detective, professional criminal, involuntary operative for Factor"),
    (62,"Bantam","Male",null,"Brown","Black","Roberto Velasquez",null,"-","good","Adventurer, boxing trainer, former boxer"),
    (63,"Batgirl","Female","Human","Green","Red","Barbara Gordon",null,"-","good","-"),
    (66,"Batgirl IV","Female","Human","Green","Black","Cassandra Cain",null,"League of Assassins (exact base is unknown)","good","-"),
    (68,"Batgirl VI","Female",null,"Blue","Blond","Stephanie Brown",null,"-","good","College student at Gotham University"),
    (69,"Batman","Male","Human","Blue","Black","Terry McGinnis",null,"Gotham City, 25th Century","good","-"),
    (70,"Batman","Male","Human","blue","black","Bruce Wayne",null,"Crest Hill, Bristol Township; Gotham County","good","Businessman"),
    (71,"Batman II","Male","Human","Blue","Black","Dick Grayson",null,"-","good","-"),
    (72,"Battlestar","Male",null,"Brown","Black","Lemar Hoskins",null,"Chicago, Illinois","good","Former wrestler, federal operative"),
    (73,"Batwoman V","Female","Human","Green","Red","Katherine Rebecca Kane",null,"-","good","-"),
    (75,"Beast","Male","Mutant","Blue","Blue","Henry Philip McCoy",null,"Dunfee, Illinois","good","Biochemist, formerly Xavier Institute for Higher Learning science and math Instructor, mutant activist, college lecturer, researcher, professional wrestler"),
    (76,"Beast Boy","Male","Human","Green","Green","Garfield Mark Logan",null,"-","good","Adventurer, Struggling Actor"),
    (78,"Ben 10","Male",null,"-","-","Benjamin Kirby Tennyson",null,"-","good","-"),
    (79,"Beta Ray Bill","Male",null,"-","No Hair","Beta Ray Bill (translation of his Korbinite name)",null,"Burning Galaxy","good","Guardian of the Korbinite race"),
    (80,"Beyonder","Male","God / Eternal","-","-",null,null,"Created in the Beyond","good","Former student"),
    (81,"Big Barda","Female","New God","Blue","Black","Barda Free",null,"-","bad","-"),
    (82,"Big Daddy","Male",null,"-","-","Damon Macready",null,"-","good","-"),
    (83,"Big Man","Male",null,"Blue","Brown","Frederick Foswell",null,"-","bad","Reporter, professional criminal"),
    (84,"Bill Harken","Male","Alpha","-","-",null,null,"-","good","-"),
    (87,"Bionic Woman","Female","Cyborg","Blue","Black","Jamie Sommers",null,"-","good","-"),
    (88,"Bird-Brain","-",null,"-","-",null,null,"-","good","-"),
    (92,"Bishop","Male","Mutant","Brown","No Hair","Lucas Bishop",null,"A mutant relocation camp in an undisclosed location on an alternate 21st Century Earth","good","(current) Adventurer, (former) Commander in the XSE (Xavier's Security Enforcers)"),
    (93,"Bizarro","Male","Bizarro","Black","Black","Bizarro",null,"-","neutral","-"),
    (95,"Black Adam","Male",null,"Brown","Black","Teth-Adam",null,"Kahndaq, Egypt","bad","-"),
    (96,"Black Bolt","Male","Inhuman","Blue","Black","Blackagar Boltagon",null,"Attilan, Atlantic Ocean","good","King of the Inhumans"),
    (97,"Black Canary","Female","Metahuman","Blue","Blond","Laurel Lance",null,"-","good","Detective/Crime-fighter, Chairperson of the Justice League of America; former florist, judo instructor"),
    (98,"Black Canary","Female","Human","Blue","Blond","Dinah Drake Lance",null,"-","good","Florist, former private investigator"),
    (99,"Black Cat","Female","Human","Green","Blond","Felicia Hardy",null,"Queens, New York","good","Cat burglar; Private investigator, founder of Cat's Eye Investigations."),
    (100,"Black Flash","Male","God / Eternal","-","-",null,null,"-","neutral","-"),
    (102,"Black Knight III","Male","Human","Brown","Brown","Dane Whitman",null,"Gloucester, Massachusetts","good","Adventurer, scientist; former crusader"),
    (103,"Black Lightning","Male",null,"Brown","No Hair","Jefferson Pierce",null,"-","good","Crime Fighter, High School teacher, Former gold-medal-winning Olympic Decathlete, formerly Secretary of Education under Presidents Pete Ross and Lex Luthor."),
    (104,"Black Mamba","Female",null,"Green","Black","Tanya Sealy",null,"Chicago, Illinois","bad","Mercenary, professional criminal, former call girl"),
    (105,"Black Manta","Male","Human","Black","No Hair","David",null,"-","bad","-"),
    (106,"Black Panther","Male","Human","Brown","Black","T'Challa",null,"Wakanda, Africa","good","King and Chieftain of Wakanda, scientist; former school teacher"),
    (107,"Black Widow","Female","Human","Green","Auburn","Natasha Romanoff",null,"-","good","Adventurer, Intelligence agent, former ballerina"),
    (109,"Blackout","Male","Demon","Red","White",null,null,"-","bad","Assassin, enforcer"),
    (110,"Blackwing","Male",null,"Blue","Black","Joseph Manfredi",null,"Professional Criminal","bad","-"),
    (111,"Blackwulf","Male","Alien","Red","White","Lucian",null,"Armechadon","-","Freedom Fighter"),
    (112,"Blade","Male","Vampire","Brown","Black","Eric Brooks",null,"Soho, London,England","good","Vampire hunter, former private investigator."),
    (114,"Bling!","Female",null,"-","-","Roxanne Washington",null,"-","good","-"),
    (115,"Blink","Female","Mutant","Green","Magenta","Clarice Ferguson",null,"Bahamas","good","Adventurer, freedom fighter"),
    (118,"Blizzard II","Male",null,"Brown","Brown","Donald Gill",null,"Newark, Delaware","bad","Adventurer; former mercenary and professional criminal"),
    (119,"Blob","Male",null,"Brown","Brown","Frederick J. Dukes",null,"Lubbock, Texas","bad","Former criminal, terrorist, government agent, carnival performer"),
    (120,"Bloodaxe","Female","Human","Blue","Brown","Jackie Lukus",null,"-","bad","Architect, former vigilante"),
    (121,"Bloodhawk","Male","Mutant","Black","No Hair","Lemuel Krug",null,"-","good","-"),
    (126,"Blue Beetle III","Male","Human","Brown","Black","Jaime Reyes",null,"Presumed to be El Paso","good","Student"),
    (127,"Boba Fett","Male","Human / Clone","Brown","Black",null,null,"Kamino","bad","Bounty Hunter"),
    (130,"Boom-Boom","Female","Mutant","Blue","Blond","Tabitha Smith",null,"-","good","Adventurer, former student, thief"),
    (135,"Box IV","-",null,"Brown","Brown / Black","Madison Jeffries",null,"Place of birth unknown","good","Inventor, former soldier"),
    (136,"Brainiac","Male","Android","Green","No Hair","Vril Dox",null,"-","bad","-"),
    (137,"Brainiac 5","Male",null,"Green","Blond","Querl Dox",null,"-","good","-"),
    (139,"Brundlefly","Male","Mutant","-","-","Seth Brundle",null,"-","-","Scientist"),
    (140,"Buffy","Female","Human","Green","Blond","Buffy Anne Summers",null,"-","good","Slayer ; (formerly) Waitress ; DoubleMeat Palace employee ; Sunnydale High Counselor"),
    (141,"Bullseye","Male","Human","blue","blond","Lester",null,"-","bad","Assassin, professional criminal, former mercenary"),
    (142,"Bumblebee","Female","Human","Brown","Black","Karen Beecher",null,"-","good","-"),
    (144,"Bushido","Male","Human","-","-","Ryuko Orsono",null,"-","good","-"),
    (145,"Cable","Male","Mutant","Blue","White","Nathan Summers",null,"Unrevealed location in the 20th Century United States","good","(current) Adventurer, (former) freedom fighter, United States government agent, mercenary, combat instructor for X-Force"),
    (146,"Callisto","Female",null,"Blue","Black","Callisto",null,"-","bad","-"),
    (147,"Cameron Hicks","Male","Alpha","-","-",null,null,"-","good","-"),
    (148,"Cannonball","Male",null,"Blue","Blond","Samuel Zachery Guthrie",null,"Cumberland County, Kentucky","good","Adventurer, peacekeeper, former student, mercenary, miner"),
    (149,"Captain America","Male","Human","blue","blond","Steve Rogers",null,"Manhattan, New York City, New York","good","Adventurer, federal official, intelligence operative; former soldier, Hydra agent, liaison between S.H.I.E.L.D. and the Avengers, police officer, teacher, sparring partner."),
    (150,"Captain Atom","Male","Human / Radiation","Blue","Silver","Nathaniel Adam",null,"-","good","Former Soldier"),
    (151,"Captain Britain","Male","Human","Blue","Blond","Brian Braddock",null,"Braddock Manor, England","good","Adventurer, formerly King of Otherworld, scientist"),
    (152,"Captain Cold","Male","Human","Brown","Brown","Leonard Snart",null,"-","neutral","Professional Criminal"),
    (154,"Captain Hindsight","Male","Human","-","Black","Jack Brolin",null,"-","good","Former Superhero; News Reporter"),
    (156,"Captain Marvel","Male","Human","Blue","Black","Billy Batson",null,"Fawcett City, United States","good","-"),
    (157,"Captain Marvel","Female","Human-Kree","Blue","Blond","Carol Danvers",null,"Boston, Massachusetts","good","Former National Aeronautics and Space Administration security Chief, former magazine editor, former freelance writer, former military intelligence officer."),
    (158,"Captain Marvel II","Male","Human","Blue","Black","Frederick Christopher Freeman",null,"-","good","Adventurer"),
    (160,"Captain Planet","Male","God / Eternal","Red","Green",null,null,"-","good","-"),
    (162,"Carnage","Male","Symbiote","Green","Red","Cletus Kasady",null,"-","bad","-"),
    (165,"Catwoman","Female","Human","Green","Black","Selina Kyle",null,"Gotham City","good","Thief"),
    (167,"Century","Male","Alien","White","White",null,null,"-","good","Tracker, adventurer"),
    (169,"Chamber","Male","Mutant","Brown","Brown","Jonothon Evan Starsmore",null,"United Kingdom","good","Adventurer"),
    (170,"Chameleon","Male",null,"-","-","Dmitri Anatoly Smerdyakov Kravinoff",null,"Russia","bad","-"),
    (171,"Changeling","Male",null,"Brown","Black","Kevin Sidney",null,"-","bad","Former substitute teacher, adventurer, subversive"),
    (172,"Cheetah","Female","Human","Green","Blond","Priscilla Rich",null,"-","bad","-"),
    (174,"Cheetah III","Female","Human","Brown","Brown","Barbara Minerva",null,"-","bad","Archaeologist, Anthropologist"),
    (176,"Chuck Norris","Male",null,"-","-","Carlos Ray Norris",null,"Ryan, Oklahoma, United States","good","-"),
    (177,"Citizen Steel","Male","Human","Green","Red","Nathan Heywood",null,"-","good","Adventurer, former Professional Football Player"),
    (178,"Claire Bennet","Female",null,"Blue","Blond","Claire Bennet",null,"-","good","High school student, cheerleader"),
    (180,"Cloak","Male",null,"brown","black","Tyrone Johnson",null,"South Boston, Massachusetts","good","Vigilante"),
    (181,"Clock King","Male","Human","Blue","Black","William Tockman",null,"-","bad","-"),
    (185,"Colossus","Male","Mutant","Silver","Black","Piotr Nikolaievitch Rasputin",null,"Ust-Ordynski Collective, near Lake Baikal, Siberia, Russia","good","(current) Adventurer, student, (former) Artist"),
    (186,"Copycat","Female","Mutant","Red","White","Vanessa Carlysle",null,"-","neutral","-"),
    (188,"Cottonmouth","Male","Human","Brown","Black","Burchell Clemens",null,"-","bad","Professional criminal"),
    (191,"Crystal","Female","Inhuman","Green","Red","Crystallia Amaquelin",null,"Attilan","good","Mother, adventuress"),
    (194,"Cyborg","Male","Cyborg","Brown","Black","Victor Stone",null,"New York City, New York","good","Adventurer, Teen Titan"),
    (195,"Cyborg Superman","Male","Cyborg","Blue","Black","Henry Henshaw",null,"-","bad","-"),
    (196,"Cyclops","Male","Mutant","Brown","Brown","Scott Summers",null,"Anchorage, Alaska","good","Leader of mutant race, adventurer, headmaster, former student, radio announcer"),
    (198,"Dagger","Female",null,"Blue","Blond","Tandy Bowen",null,"Shaker Heights, Ohio","good","Vigilante"),
    (200,"Daphne Powell","Female",null,"-","-","Daphne Powell",null,"-","good","Student"),
    (201,"Daredevil","Male","Human","Blue","Red","Matt Murdock",null,"New York City, New York","good","Adventurer, vigilante, Attorney at Law"),
    (202,"Darkhawk","Male","Human","Brown","Brown","Christopher Powell",null,"Queens, New York","good","Retired Superhero"),
    (203,"Darkman","Male",null,"-","-","Peyton Westlake",null,"-","good","Scientist"),
    (204,"Darkseid","Male","New God","Red","No Hair","Uxas",null,"-","bad","Dictator of Apokolips"),
    (206,"Darkstar","Female","Mutant","Brown","Blond","Laynia Petrovna",null,"Minks, USSR","good","Occupation unknown"),
    (207,"Darth Maul","Male","Dathomirian Zabrak","Yellow / Red","-",null,null,"Dathomir","bad","-"),
    (208,"Darth Vader","Male","Cyborg","Yellow","No Hair","Anakin Skywalker",null,"Tatooine","bad","Sith Lord, Supreme Commander of the Imperial Fleet"),
    (209,"Dash","Male","Human","Blue","Blond","Dashiell Robert Parr",null,"-","good","-"),
    (210,"Data","Male","Android","Yellow","Brown","Data",null,"-","good","Lieutenant commander"),
    (211,"Dazzler","Female","Mutant","Blue","Blond","Alison Blaire",null,"Gardendale, Long Island, New York","good","Adventurer, singer, former actress, model, revolutionary"),
    (212,"Deadman","Male","Human","Blue","Black","Boston Brand",null,"-","good","Wandering Spirit, Former Circus Aerialist"),
    (213,"Deadpool","Male","Mutant","Brown","No Hair","Wade Wilson",null,"Canada","neutral","Mercenary; former enforcer, government operative, sumo wrestler, soldier, assassin, anti-hero, others"),
    (214,"Deadshot","Male","Human","Brown","Brown","Floyd Lawton",null,"-","bad","-"),
    (215,"Deathlok","Male","Cyborg","Brown","Grey","Luther Manning",null,"-","good","-"),
    (216,"Deathstroke","Male","Human","Blue","White","Slade Joseph Wilson",null,"-","neutral","Mercenary; Former Soldier, Big-Game Hunter"),
    (217,"Demogoblin","Male","Demon","Red","No Hair",null,null,"-","bad","Demonic Redeemer"),
    (218,"Destroyer","Male",null,"-","-",null,null,"Created in Asgard","bad","-"),
    (219,"Diamondback","Male","Human","Brown","Black","Willis Stryker",null,"-","bad","Criminal"),
    (220,"DL Hawkins","Male",null,"-","-","Daniel Lawrence Hawkins",null,"-","good","Construction worker, Firefighter"),
    (221,"Doc Samson","Male","Human / Radiation","Blue","Green","Leonard Samson",null,"Tulsa, Oklahoma","good","Psychiatrist, teacher, adventurer, former special consultant to Gamma Base"),
    (222,"Doctor Doom","Male","Human","Brown","Brown","Victor von Doom",null,"Haasenstadt, Latveria","bad","Monarch"),
    (224,"Doctor Fate","Male","Human","Blue","Blond","Kent Nelson",null,"-","good","-"),
    (225,"Doctor Octopus","Male","Human","Brown","Brown","Otto Octavius",null,"Schenectady, New York","bad","Former atomic-research consultant, criminal mastermind"),
    (226,"Doctor Strange","Male","Human","Grey","Black","Stephen Strange",null,"Philadelphia, Pennsylvania","good","Sorcerer Supreme, retired neurosurgeon"),
    (227,"Domino","Female","Human","Blue","Black","Neena Thurman",null,"Project: Armageddon base, Everglades, Florida","good","-"),
    (228,"Donatello","Male","Mutant","Green","No Hair",null,null,"-","good","-"),
    (230,"Doomsday","Male","Alien","Red","White","Doomsday",null,"Krypton","bad","Destroyer"),
    (231,"Doppelganger","Male",null,"White","No Hair",null,null,"The Dimension of Manifestations","bad","-"),
    (232,"Dormammu","Male",null,"Yellow","No Hair","Dormammu",null,"Faltine Dimension","bad","Despot, conqueror"),
    (233,"Dr Manhattan","Male","Human / Cosmic","White","No Hair","Jonathan Osterman",null,"-","good","Scientist"),
    (234,"Drax the Destroyer","Male","Human / Altered","Red","No Hair","Arthur Sampson Douglas",null,"Burbank, California","good","-"),
    (235,"Ego","-",null,"-","-","Ego",null,"The Black Galaxy","bad","Inapplicable"),
    (236,"Elastigirl","Female","Human","Brown","Brown","Helen Parr",null,"-","good","-"),
    (237,"Electro","Male","Human","Blue","Auburn","Maxwell Dillon",null,"-","bad","Professional criminal"),
    (238,"Elektra","Female","Human","Blue","Black","Elektra Natchios",null,"-","good","Assassin, adventurer, mercenary, former student, dancer"),
    (239,"Elle Bishop","Female",null,"Blue","Blond",null,null,"-","bad","Agent of the Company"),
    (240,"Elongated Man","Male",null,"Blue","Red","Ralph Dibny",null,"-","good","Detective"),
    (241,"Emma Frost","Female",null,"Blue","Blond","Emma Frost",null,"Boston, Massachusetts","good","-"),
    (242,"Enchantress","Female","Human","Blue","Blond","June Moone",null,"-","good","Artist; Magician"),
    (245,"Ethan Hunt","Male","Human","Brown","Brown","Ethan Hunt",null,"Madison, Wisconsin, United States of America","good","IMF Agent, Training Officer (former), Field Agent, Field Team Leader"),
    (246,"Etrigan","Male","Demon","Red","No Hair","Jason Blood",null,"Hell","neutral","-"),
    (247,"Evil Deadpool","Male","Mutant","White","Red","Wade Wilson",null,"-","bad","Mercenary, Assasin"),
    (248,"Evilhawk","Male","Alien","Red","Black","Dargin Bokk",null,"-","bad","Crimelord"),
    (249,"Exodus","Male","Mutant","Blue","Black","Bennet du Paris",null,"-","bad","Terrorist, would-be conqueror, Former leader of the Acolytes, Crusader"),
    (251,"Falcon","Male","Human","Brown","Black","Sam Wilson",null,"New York, New York","good","Crimefighter, (former) freelance artist"),
    (252,"Fallen One II","Male",null,"Black","Blue",null,null,"-","bad","-"),
    (253,"Faora","Female","Kryptonian","-","-","Faora Hu-Ul",null,"-","bad","Serial killer"),
    (254,"Feral","-",null,"Yellow (without irises)","Orange / White","Maria Callasantos",null,"Place of birth unknown","good","Formerly Adventurer, Terrorist"),
    (256,"Fin Fang Foom","Male","Kakarantharaian","Red","No Hair",null,null,"-","good","-"),
    (257,"Firebird","Female",null,"Brown","Black","Bonita Juarez",null,"Buena Vista, New Mexico","good","Social worker, adventurer"),
    (258,"Firelord","-",null,"White","Yellow","Pyreus Kril",null,"Xander, planet in Tranta System, Andromeda Galaxy","good","Former starship captain, former herald of Galactus"),
    (259,"Firestar","Female","Mutant","Green","Red","Angelica Jones",null,"Place of birth unknown","good","Student"),
    (260,"Firestorm","Male",null,"Brown","Black","Jason Rusch",null,"-","good","University student; former food server at Bryson's Family Treat; former mascot at Ho-Ho Charlie's Chicken Shack; former intern at S.T.A.R. Labs"),
    (261,"Firestorm","Male","Human","Blue","Auburn","Ronald Raymond",null,"-","good","Adventurer; former employee of Bun 'n Run"),
    (263,"Flash","Male","Human","Blue","Brown / White","Jay Garrick",null,"Hibbardsville, Kansas","good","Research Scientist, part-time Director of Garrick Laboratories"),
    (265,"Flash II","Male","Black Racer","Blue","Blond","Barry Allen",null,"Fallville, Iowa","good","Forensic Scientist"),
    (266,"Flash III","Male","Human","-","-","Wally West",null,"Blue Valley, Nebraska","good","Adventurer, Mechanic for the KCPD"),
    (267,"Flash IV","Male","Human","Yellow","Auburn","Bartholomew Allen II",null,"-","good","Police trainee"),
    (268,"Forge","-",null,"Brown","Black",null,null,"Unrevealed, presumably in the American West","good","Inventor working for the U.S. government, former soldier"),
    (269,"Franklin Richards","Male","Mutant","Blue","Blond","Franklin  Richards",null,"New York, New York","good","Student"),
    (270,"Franklin Storm","-",null,"Blue","Grey","Dr. Franklin Storm",null,"Place of birth unknown","good","Surgeon"),
    (271,"Frenzy","Female",null,"Brown","Black","Joanna Cargill",null,"-","bad","Mercenary"),
    (273,"Galactus","Male","Cosmic Entity","Black","Black","Galan",null,"(Galan) Taa; (Galactus) the Cosmic Egg","neutral","Planet Devourer, Third Force of the Universe - balance between Eternity and Death, Nullifying Abraxas' Influence on the Multiverse, Third Face of the Living Tribunal - representing Equity"),
    (274,"Gambit","Male","Mutant","Red","Brown","Remy Etienne LeBeau",null,"New Orleans, Louisiana","good","Jean Grey School for Higher Learning, Salem Center, Westchester County, New York; formerly Utopia, San Francisco Bay, California; Xavier Institute, Salem Center, Westchester County, New York; New Orleans; Paris; Cairo; Illinois"),
    (275,"Gamora","Female","Zen-Whoberian","Yellow","Black","Gamora Zen Whoberi Ben Titan",null,"Planet Zen Whoberi, Silican System, Milky Way","good","Assassin, mercenary, adventurer"),
    (277,"Gary Bell","Male","Alpha","-","-","Gary Bell",null,"-","good","-"),
    (278,"General Zod","Male","Kryptonian","Black","Black","Dru-Zod",null,"Krypton","bad","-"),
    (280,"Ghost Rider","Male","Demon","Red","No Hair","Johnny Blaze",null,"Waukegan, Illinois","good","Former stunt motorcyclist"),
    (284,"Giganta","Female",null,"Green","Red","Doris Zuel",null,"-","bad","Criminal, former Scientist, Professor at Ivy University"),
    (285,"Gladiator","Male","Strontian","Blue","Blue","Kallark",null,"-","neutral","Majestor of the Shi'ar Empire; Former Praetor of the Imperial Guard; possibly former Herald of Galactus"),
    (286,"Goblin Queen","Female",null,"Green","Red","Madelyne Jennifer Pryor",null,"Created in Sinister's Labs, Nebraska","bad","-"),
    (287,"Godzilla","-","Kaiju","-","-","Gojira",null,"-","bad","-"),
    (288,"Gog","Male",null,"-","-",null,null,"-","bad","-"),
    (289,"Goku","Male","Saiyan","-","-","Kakarot",null,"-","good","-"),
    (294,"Gorilla Grodd","Male","Gorilla","Yellow","Black","Grodd",null,"-","bad","-"),
    (296,"Gravity","Male","Human","Blue","Brown","Greg Willis",null,"Sheboygan, Wisconsin","good","Student"),
    (297,"Greedo","Male","Rodian","Purple","-","Greedo",null,"Rodia","bad","Bounty Hunter"),
    (298,"Green Arrow","Male","Human","Green","Blond","Oliver Queen",null,"-","good","Professional Crime-fighter; Multi-Billionaire"),
    (299,"Green Goblin","Male","Human","Blue","Auburn","Norman Osborn",null,"Hartford, Connecticut","bad","Professional criminal, owner and president of Osborn Industries"),
    (300,"Green Goblin II","Male",null,"Blue","Auburn","Harold Osborn",null,"New York City","bad","-"),
    (303,"Groot","Male","Flora Colossus","Yellow","-","Groot",null,"-","good","-"),
    (305,"Guy Gardner","Male","Human-Vuldarian","Blue","Red","Guy Gardner",null,"Baltimore, Maryland","good","Former High School gym teacher; former bar owner; currently Honor guard of the Green Lantern Corps"),
    (306,"Hal Jordan","Male","Human","Brown","Brown","Hal Jordan",null,"Coast City, California","good","Adventurer, Air Force Test Pilot"),
    (307,"Han Solo","Male","Human","Brown","Brown","Han Solo",null,"Corellia","good","-"),
    (308,"Hancock","Male","Human","Brown","Black","John Hancock",null,"-","good","-"),
    (309,"Harley Quinn","Female","Human","Blue","Blond","Harley Quinn",null,"-","bad","Psychiatrist"),
    (310,"Harry Potter","Male","Human","Green","Black","Harry James Potter",null,"-","good","Head of the Department of Magical Law Enforcement["),
    (311,"Havok","Male","Mutant","Blue","Blond","Alexander Summers",null,"Honolulu, Hawaii","good","Currently Adventurer, formerly Graduate student in geophysics"),
    (312,"Hawk","Male",null,"Red","Brown","Henry Hall",null,"-","good","-"),
    (313,"Hawkeye","Male","Human","Blue","Blond","Clint Barton",null,"Waverly, Iowa","good","Adventurer"),
    (314,"Hawkeye II","Female","Human","Blue","Black","Katherine Elizabeth Bishop",null,"New York City, New York","good","Student; Adventurer; Fugitive"),
    (315,"Hawkgirl","Female",null,"Green","Red","Kendra Saunders",null,"-","good","Adventurer, Film School Student, Temp Curator of the Stonechat Museum"),
    (320,"Heat Wave","Male","Human","Blue","No Hair","Mick Rory",null,"-","bad","Professional Criminal"),
    (321,"Hela","Female","Asgardian","Green","Black",null,null,"-","bad","Asgardian Goddess of Death, former Ruler of Hel and Niffleheim"),
    (322,"Hellboy","Male","Demon","Gold","Black","Anung Un Rama",null,"-","good","-"),
    (323,"Hellcat","Female","Human","Blue","Red","Patricia Walker",null,"Centerville, CA USA","good","Housemaker, model, adventurer, supernatural investigator"),
    (325,"Hercules","Male","Demi-God","Blue","Brown","Heracles",null,"Thebes, Greece","good","Adventurer, Olympian God of Strength and Labor, later Olympian God of Heroes"),
    (327,"Hit-Girl","Female","Human","-","-","Mindy McCready",null,"-","good","-"),
    (330,"Hope Summers","Female",null,"Green","Red","Hope Summers",null,"-","good","-"),
    (332,"Hulk","Male","Human / Radiation","Green","Green","Bruce Banner",null,"Dayton, Ohio","good","Nuclear physicist, Agent of S.H.I.E.L.D."),
    (333,"Human Torch","Male","Human / Radiation","Blue","Blond","Johnny Storm",null,"Glenville, Long Island, New York","good","Adventurer"),
    (334,"Huntress","Female",null,"Blue","Black","Helena Rosa Bertinelli",null,"-","good","Vigilante; High school English teacher"),
    (335,"Husk","Female","Mutant","Blue","Blond","Paige Elisabeth Guthrie",null,"Cumberland, Kentucky","good","Adventurer; formerly student, activist"),
    (336,"Hybrid","Male","Symbiote","Brown","Black","Scott Washington",null,"Bedford-Stuyvesant, Brooklyn, New York City","good","-"),
    (337,"Hydro-Man","Male",null,"Brown","Brown","Morris Bench",null,"Bronx, New York","bad","Professional Criminal; former crewman of cargo ship"),
    (338,"Hyperion","Male","Eternal","Blue","Red","Mark Milton",null,"-","good","Adventurer; (Formerly) Cartoonist, government agent"),
    (339,"Iceman","Male","Mutant","Brown","Brown","Bobby Drake",null,"Fort Washington, Long Island, New York","good","Adventurer, formerly teacher, accountant, student"),
    (340,"Impulse","Male","Human","Yellow","Auburn","Bartholomew Allen II",null,"-","good","Adventurer, Student"),
    (341,"Indiana Jones","Male","Human","-","-","Indiana Jones",null,"Princeton, New Jersey","good","Archaeologist"),
    (342,"Indigo","Female","Alien","-","Purple","Iroque",null,"-","neutral","Leader of the Indigo Tribe"),
    (343,"Ink","Male","Mutant","Blue","No Hair","Eric Gitter",null,"-","good","-"),
    (344,"Invisible Woman","Female","Human / Radiation","blue","Blond","Susan Storm Richards",null,"Glenville, Long Island, New York","good","Member of the Fantastic Four, financial manager for Fantastic Four Inc, occasional model and actress"),
    (345,"Iron Fist","Male","Human","Blue","Blond","Danny Rand",null,"-","good","Adventurer; formerly co-owner of Rand-Meachum, Inc., bodyguard, private investigator, research assistant, warrior"),
    (346,"Iron Man","Male","Human","Blue","Black","Tony Stark",null,"Long Island, New York","good","Inventor, Industrialist; former United States Secretary of Defense"),
    (347,"Iron Monger","Male",null,"Blue","No Hair","Obadiah Stane",null,"-","bad","CEO Stane International"),
    (348,"Isis","Female",null,"-","-","Adrianna Tomaz",null,"-","good","Adventurer, formerly First Lady of Kahndaq, former slave"),
    (350,"Jack of Hearts","Male","Human","Blue / White","Brown","Jonathan Hart",null,"New Haven, Connecticut","good","Adventurer"),
    (351,"Jack-Jack","Male","Human","Blue","Brown","Jack-Jack Parr",null,"-","good","-"),
    (352,"James Bond","Male","Human","blue","Blond","James Bond",null,"-","good","00 Agent"),
    (353,"James T. Kirk","Male","Human","Hazel","Brown","James T. Kirk",null,"Riverside, Iowa, Earth","good","Captain"),
    (354,"Jar Jar Binks","Male","Gungan","Yellow","-","Jar Jar Binks",null,"Naboo","good","-"),
    (355,"Jason Bourne","Male","Human","-","-","Jason Bourne",null,"-","good","-"),
    (356,"Jean Grey","Female","Mutant","Green","Red","Jean Grey",null,"-","good","Adventurer"),
    (357,"Jean-Luc Picard","Male","Human","-","-","Jean-Luc Picard",null,"La Barre, France, Earth","good","Commanding officer USS Enterprise (NCC-1701-E)"),
    (358,"Jennifer Kale","Female",null,"Blue","Blond","Jennifer Kale",null,"Citrusville, Florida","good","Sorceress, student"),
    (360,"Jessica Cruz","Female","Human","Green","Brown","Jessica Cruz",null,"-","good","-"),
    (361,"Jessica Jones","Female","Human","Brown","Brown","Jessica Campbell Jones Cage",null,"Forrest Hills, New York City","good","Special Consultant to \"The Pulse\", a Daily Bugle supplement; formerly private investigator, adventurer, short-time vigilante"),
    (364,"Jim Powell","Male",null,"-","-","Jim Powell",null,"-","good","Police Sketch Artist"),
    (365,"JJ Powell","Male",null,"-","-","JJ Powell",null,"-","good","Student"),
    (367,"John Constantine","Male","Human","Blue","Blond","John Constantine",null,"-","good","-"),
    (369,"John Wraith","Male",null,"Brown","Black","John Wraith",null,"-","good","Former Spy, Government Operative, Mercenary, Soldier"),
    (370,"Joker","Male","Human","Green","Green","Jack Napier",null,"-","bad","-"),
    (371,"Jolt","Female",null,"Blue","Black","Helen Takahama",null,"Ojai, California","good","Adventurer"),
    (372,"Jubilee","Female","Mutant","Red","Black","Jubilation Lee",null,"Beverly Hills, California","good","Student, Adventurer"),
    (373,"Judge Dredd","Male","Human","-","-","Joseph Dredd",null,"Mega City One","good","Mega-City Judge"),
    (374,"Juggernaut","Male","Human","Blue","Red","Cain Marko",null,"Berkeley, California","neutral","Adventurer formerly Professional criminal, mercenary, soldier"),
    (375,"Junkpile","Male","Mutant","-","-",null,null,"-","bad","Mercenary; Former member of S.H.I.E.L.D."),
    (376,"Justice","Male","Human","Hazel","Brown","Vance Astrovik",null,"-","good","Adventurer"),
    (379,"Kang","Male",null,"Brown","Brown","Nathaniel Richards",null,"Other Earth, 31st century","bad","-"),
    (380,"Kathryn Janeway","Female","Human","-","-","Kathryn Janeway",null,"Bloomington, Indiana, Earth","good","Fleet Commander"),
    (381,"Katniss Everdeen","Female","Human","-","-","Katniss Everdeen",null,"-","good","-"),
    (382,"Kevin 11","Male","Human","-","Black","Kevin Ethan Levin",null,"-","good","-"),
    (383,"Kick-Ass","Male","Human","Blue","Blond","Dave Lizewski",null,"New York City","good","Student"),
    (384,"Kid Flash","Male","Human","Green","Red","Wallace Rudolph West",null,"Blue Valley, Nebraska","good","-"),
    (386,"Killer Croc","Male","Metahuman","Red","No Hair","Waylon Jones",null,"-","bad","-"),
    (387,"Killer Frost","Female","Human","Blue","Blond","Caitlin Snow",null,"-","bad","Scientist"),
    (388,"Kilowog","Male","Bolovaxian","Red","No Hair",null,null,"Bolovax Vik","good","-"),
    (389,"King Kong","Male","Animal","Yellow","Black","King Kong",null,"Skull Island","good","-"),
    (390,"King Shark","Male","Animal","Black","No Hair","Nanaue",null,"-","bad","Professional Criminal"),
    (391,"Kingpin","Male","Human","Blue","No Hair","Wilson Grant Fisk",null,"New York City area","bad","Criminal organizer and mastermind, president and owner of legitimate businesses"),
    (392,"Klaw","Male","Human","Red","No Hair","Ulysses Klaw",null,"Vlaardingen, Netherlands","bad","Criminal, former Scientist"),
    (393,"Kool-Aid Man","Male",null,"Black","No Hair",null,null,"-","good","-"),
    (394,"Kraven II","Male","Human","Brown","Black","Alyosha Kravinoff",null,"-","bad","-"),
    (395,"Kraven the Hunter","Male","Human","Brown","Black","Sergei Kravinoff",null,"Volgograd (formerly Stalingrad), Russia","bad","Professional game hunter, mercenary"),
    (396,"Krypto","Male","Kryptonian","Blue","White","Krypto the Superdog",null,"-","good","-"),
    (397,"Kyle Rayner","Male","Human","Green","Black","Kyle Rayner",null,"North Hollywood, Los Angeles, California","good","Green Lantern, Adventurer, Artist"),
    (398,"Kylo Ren","Male","Human","-","-","Ben Solo",null,"-","bad","-"),
    (400,"Lady Deathstrike","Female","Cyborg","Brown","Black","Yuriko Oyama",null,"Osaka, Japan","bad","-"),
    (401,"Leader","Male",null,"Green","No Hair","Samuel Sterns",null,"Boise, Idaho","bad","-"),
    (402,"Leech","Male",null,"-","-",null,null,"-","good","Survivor, former student"),
    (403,"Legion","Male","Mutant","Green / Blue","Black","David Haller",null,"Israel","good","Adventurer, Student"),
    (404,"Leonardo","Male","Mutant","Blue","No Hair","Leonardo",null,"-","good","Ninja"),
    (405,"Lex Luthor","Male","Human","Green","No Hair","Lex Luthor",null,"-","bad","Owner of LexCorp"),
    (406,"Light Lass","Female",null,"Blue","Red","Ayla Ranzz",null,"-","good","-"),
    (407,"Lightning Lad","Male",null,"Blue","Red","Garth Ranzz",null,"-","good","Legionnaire"),
    (408,"Lightning Lord","Male",null,"Blue","Red","Mekt Ranzz",null,"-","bad","-"),
    (409,"Living Brain","-",null,"Yellow","-",null,null,"-","bad","Robot"),
    (410,"Living Tribunal","-","Cosmic Entity","Blue","No Hair",null,null,"-","neutral","-"),
    (412,"Lizard","Male","Human","Red","No Hair","Curtis Connors",null,"Coral Gables, Florida","bad","Research biologist"),
    (413,"Lobo","Male","Czarnian","Red","Black","Lobo",null,"-","neutral","Assassin, Bounty Hunter, Priest"),
    (414,"Loki","Male","Asgardian","Green","Black","Loki Laufeyson",null,"Jotunheim, Asgard","bad","God of evil; former god of mischief and madness"),
    (415,"Longshot","Male","Human","Blue","Blond",null,null,"-","good","freedom fighter, stuntman rebel, adventurer"),
    (416,"Luke Cage","Male","Human","Brown","Black","Luke Cage",null,"Harlem, New York City","good","Adventurer, bar owner, bodyguard, mercenary; formerly theater owner, private investigator, various odd jobs"),
    (418,"Luke Skywalker","Male","Human","Blue","Blond","Luke Skywalker",null,"Tatooine","good","-"),
    (419,"Luna","Female","Human","-","-","Luna Maximoff",null,"Attilan, Blue Area of the Moon","good","-"),
    (421,"Mach-IV","Male",null,"Brown","Brown","Abner Jenkins",null,"Baltimore, Maryland","bad","Adventurer; former master mechanic, professional criminal, mercenary"),
    (422,"Machine Man","-",null,"Red","Black","X-51, Aaron Stack",null,"Central City, California","good","Insurance Investigator"),
    (423,"Magneto","Male","Mutant","Grey","White","Erik Magnus Lensherr",null,"Unrevealed, probably somewhere in Northern Europe","bad","Currently Revolutionary and Conqueror, formerly Volunteer Orderly, Secret Agent"),
    (424,"Magog","Male",null,"Blue","Blond","David Reid",null,"-","good","-"),
    (425,"Magus","Male",null,"Black","-",null,null,"Kvch (Technarchy?s home planet)","bad","Ruler of the Technarchy"),
    (426,"Man of Miracles","-","God / Eternal","Blue","Silver",null,null,"-","-","-"),
    (427,"Man-Bat","Male","Human","Brown","Brown","Robert Kirkland Langstrom",null,"Chicago, Illinois","neutral","Zoologist"),
    (428,"Man-Thing","Male",null,"Red","No Hair","Dr. Theodore Sallis",null,"-","good","-"),
    (429,"Man-Wolf","Male",null,"Brown","Auburn","John Jameson",null,"New York, New York","good","Employed by Dept. of Social Services, Queens; former astronaut, test pilot, security chief for Ravenscroft Institute"),
    (430,"Mandarin","Male","Human","Blue","White","Khan",null,"China","bad","Would-be conqueror; former janitor, businessman and crimelord, government administrator"),
    (431,"Mantis","Female","Human-Kree","Green","Black",null,null,"Vietnam","good","Celestial Madonna, former adventuress, former bar-maid/prostitute/exotic dancer"),
    (432,"Martian Manhunter","Male","Martian","Red","No Hair","J'onn J'onzz",null,"-","good","-"),
    (433,"Marvel Girl","Female",null,"Green","Red","Rachel Anne Summers",null,"-","good","Adventurer"),
    (435,"Master Chief","Male","Human / Altered","Brown","Brown","John-117",null,"Elysium City, Eridanus II","good","Master Chief Petty Officer of the Navy"),
    (436,"Match","Male",null,"Black","Black","Kent Connor",null,"-","bad","-"),
    (437,"Matt Parkman","Male",null,"-","-","Matthew Parkman",null,"-","good","NYPD detective"),
    (438,"Maverick","Male",null,"Blue","Black","Christopher Bradley",null,"-","good","Mercenary; former adventurer, student"),
    (439,"Maxima","Female",null,"Brown","Red",null,null,"Almerac","bad","Adventurer, Queen of the Almerac Empire"),
    (440,"Maya Herrera","Female",null,"-","-","Maya Herrera",null,"Dominican Republic","good","-"),
    (441,"Medusa","Female","Inhuman","Green","Red","Medusalith Amaquelin Boltagon",null,"Island of Attilan, Atlantic Ocean","good","Queen, Royal interpreter"),
    (442,"Meltdown","Female",null,"Blue","Blond","Tabitha Smith",null,"Roanoke, Virginia","good","Adventurer, former student, thief"),
    (443,"Mephisto","Male",null,"White","Black",null,null,"Hell","bad","Lord of a realm of Hell"),
    (444,"Mera","Female","Atlantean","Blue","Red","Mera",null,"-","good","Former queen of Atlantis; Former queen of Dimension Aqua"),
    (445,"Metallo","Male","Android","Green","Brown","John Corben",null,"-","bad","Professional criminal"),
    (448,"Metron","Male",null,"Blue","Black","Metron",null,"-","good","Scientist, seeker of knowledge"),
    (449,"Micah Sanders","Male",null,"Brown","Black","Micah Sanders",null,"-","good","Elementary school student"),
    (450,"Michelangelo","Male","Mutant","Blue","-",null,null,"-","good","-"),
    (451,"Micro Lad","Male",null,"Grey","Brown","Gim Allon",null,"-","good","-"),
    (452,"Mimic","Male",null,"Brown","Brown","Calvin Montgomery Rankin",null,"Passiac, New Jersey","good","-"),
    (454,"Misfit","Female",null,"Blue","Red","Charlotte Gage-Radcliffe",null,"-","good","-"),
    (455,"Miss Martian","Female",null,"Red","Red","M'gann M'orzz",null,"Mars","good","Adventurer"),
    (456,"Mister Fantastic","Male","Human / Radiation","Brown","Brown","Reed Richards",null,"Central City, California","good","Scientist, adventurer"),
    (457,"Mister Freeze","Male","Human","-","-","Victor Fries",null,"-","bad","-"),
    (458,"Mister Knife","Male","Spartoi","Blue","Brown","J'son",null,"Spartax, Spartoi Empire, near the Shi'ar Galaxy","bad","Crimelord; former emperor, prince"),
    (459,"Mister Mxyzptlk","Male","God / Eternal","-","-","Mr. Mxyzptlk",null,"-","bad","-"),
    (460,"Mister Sinister","Male","Human / Altered","Red","Black","Nathaniel Essex",null,"London, England","bad","Geneticist, Criminal, biologist and mutant-supremacist"),
    (461,"Mister Zsasz","Male","Human","Blue","Blond","Victor Zsasz",null,"-","bad","Serial Killer"),
    (462,"Mockingbird","Female","Human","Blue","Blond","Barbara Morse",null,"San Diego, California","good","Adventurer; former counter-terrorist agent, private investigator, government operative, S.H.I.E.L.D. agent, biologist"),
    (463,"MODOK","Male","Cyborg","White","Brownn","George Tarleton",null,"-","bad","Would-be conqueror, AIM leader, terrorist; former AIM agent, technician"),
    (467,"Molten Man","Male",null,"Gold","Gold","Mark Raxton",null,"-","bad","Security guard for Osborn industries, former criminal, lab assistant"),
    (469,"Monica Dawson","Female",null,"-","-","Monica Dawson",null,"-","good","Fast food service"),
    (470,"Moon Knight","Male","Human","Brown","Brown","Marc Spector",null,"Chicago, Illinois","good","Adventurer, entrepreneur; former prize fighter, spy, soldier, mercenary, cab driver"),
    (471,"Moonstone","Female",null,"Blue","Blond","Karla Sofen",null,"Van Nuys, California","bad","former Adventurer, Psychiatrist"),
    (472,"Morlun","Male",null,"White / Red","Black","Morlun",null,"-","bad","-"),
    (474,"Moses Magnum","Male",null,"Brown","Black","Moses Magnum",null,"-","bad","Terrorist, president of Magnum Munitions; former ruler of Canaan"),
    (475,"Mr Immortal","Male","Mutant","Blue","Blond","Craig Hollis",null,"-","good","-"),
    (476,"Mr Incredible","Male","Human","Blue","Blond","Robert Parr",null,"-","good","-"),
    (477,"Ms Marvel II","Female",null,"Blue","Red","Sharon Ventura",null,"Pullman, Washington","good","Wanderer, former adventurer, wrestler, stunt woman, scuba diver, motorcycle performer"),
    (478,"Multiple Man","Male",null,"Blue","Brown","James Arthur",null,"Los Alamos, New Mexico","good","Private investigator (formerly) Farmer, Adventurer"),
    (479,"Mysterio","Male","Human","Brown","No Hair","Quentin Beck",null,"New York, New York","bad","Criminal; former Hollywood special effects designer and stunt man"),
    (480,"Mystique","Female","Mutant","Yellow (without irises)","Red / Orange","Raven Darkholme",null,"-","bad","Special operative for Germany and the United States governments, (former) German Freedom Fighter, special operative in the Weapon X Project Team"),
    (481,"Namor","Male","Atlantean","Grey","Black","Namor McKenzie",null,"Atlantis","good","King of Atlantis, Adventurer; former warrior, commando, CEO"),
    (483,"Namora","Female",null,"Blue","Blond","Aquaria Nautica Neptunia",null,"Unnamed Atlantean outpost","good","-"),
    (484,"Namorita","Female",null,"Blue","Blond","Namorita Prentiss",null,"Atlantis Outskirts","good","Superhero, formerly Leader of Atlantis"),
    (485,"Naruto Uzumaki","Male","Human","-","-",null,null,"-","good","-"),
    (487,"Nebula","Female","Luphomoid","Blue","No Hair",null,null,"-","bad","-"),
    (488,"Negasonic Teenage Warhead","Female","Mutant","Black","Black","Ellie Phimister",null,"-","good","-"),
    (489,"Nick Fury","Male","Human","Brown","Brown / White","Nicholas Joseph Fury",null,"New York City","good","S.H.I.E.L.D. director; former S.H.I.E.L.D. agent, intelligence agent, soldier and commando leader, parachuting instructor, stunt flyer"),
    (490,"Nightcrawler","Male",null,"Yellow","Indigo","Kurt Wagner",null,"Somewhere in the Bavarian Alps","good","Adventurer, Teacher"),
    (491,"Nightwing","Male","Human","Blue","Black","Dick Grayson",null,"Gotham City","good","Vigilante and detective, former police officer, former Circus Acrobat"),
    (492,"Niki Sanders","Female",null,"Blue","Blond","Nicole Sanders",null,"-","good","Former casino worker and online webcam operator; currently an agent of the Company"),
    (493,"Nina Theroux","Female","Alpha","-","-",null,null,"-","good","-"),
    (495,"Northstar","Male",null,"Blue","Black","Jean-Paul Beaubier",null,"Montreal, Qu?bec, Canada","good","Former terrorist, adventurer, teacher, businessman, novelist, professional skier, trapeze artist, thief"),
    (496,"Nova","Male","Human","Brown","Brown","Richard Rider",null,"Queens, NY","good","Superhero, also works parttime at Marvel Burger"),
    (497,"Nova","Female","Human / Cosmic","White","Red","Frankie Raye",null,"-","good","-"),
    (498,"Odin","Male","God / Eternal","Blue","White","Odin Borson",null,"Asgard","good","Deity, Monarch of Asgard, Asgardian God of the Sky, Wind, Wisdom, Crafts, Time, and the Dead, Warrior"),
    (499,"Offspring","Male",null,"-","-","Luke O'Brian",null,"-","good","-"),
    (502,"One Punch Man","Male","Human","-","No Hair","Saitama",null,"-","good","Superhero, Sensei"),
    (503,"One-Above-All","-","Cosmic Entity","-","-",null,null,"-","neutral","-"),
    (504,"Onslaught","Male","Mutant","Red","No Hair","Onslaught",null,"-","bad","Would-be destroyer"),
    (505,"Oracle","Female","Human","Blue","Red","Barbara Gordon",null,"-","good","Computer hacker and Coordinator of the Birds of Prey; Former student; former librarian; former vigilante"),
    (506,"Osiris","Male",null,"Brown","Brown","Amon Tomaz",null,"-","good","-"),
    (508,"Ozymandias","Male","Human","Blue","Blond","Adrian Veidt",null,"-","bad","-"),
    (509,"Parademon","-","Parademon","-","-",null,null,"Apokalips","bad","-"),
    (510,"Paul Blart","Male","Human","-","-","Paul Blart",null,"-","good","-"),
    (514,"Penguin","Male","Human","Blue","Black","Oswald Chesterfield Cobblepot",null,"-","bad","Trader"),
    (516,"Phantom Girl","Female",null,"Blue","Black","Tinya Wazzo",null,"-","good","-"),
    (517,"Phoenix","Female","Mutant","Green","Red","Jean Grey",null,"-","good","Adventurer"),
    (518,"Plantman","Male","Mutant","Green","Grey","Samuel Smithers",null,"London, England","bad","Professional Criminal, formerly Gardner"),
    (520,"Plastic Man","Male","Human","Blue","Black","Patrick O'Brian",null,"-","good","Government Agent"),
    (521,"Plastique","Female",null,"Blue","Red","Bette Sans Souci",null,"-","bad","Government Agent, former Terrorist, Mercenary"),
    (522,"Poison Ivy","Female","Human","Green","Red","Pamela Isley",null,"Seattle, Washington","bad","Criminal, Botanist"),
    (523,"Polaris","Female","Mutant","Green","Green","Lorna Dane",null,"Presumably northern California - not confirmed","good","Adventurer, former U.S. government operative, former graduate student in geophysics"),
    (524,"Power Girl","Female","Kryptonian","blue","blond","Kara Zor-L",null,"-","good","-"),
    (526,"Predator","Male","Yautja","-","-","Yautja",null,"Yautja Prime","bad","-"),
    (527,"Professor X","Male","Mutant","Blue","No Hair","Charles Francis Xavier",null,"New York, New York","good","Mutant leader, mutant rights activist, geneticist, teacher, adventurer, heir, formerly headmaster, soldier (US Army)"),
    (528,"Professor Zoom","Male","Human","Blue","Strawberry Blond","Eobard Thawne",null,"-","bad","-"),
    (529,"Psylocke","Female","Mutant","Blue","Purple","Elizabeth Braddock",null,"Braddock Manor, England","good","Adventurer, formerly a STRIKE operative, fashion model"),
    (530,"Punisher","Male","Human","Blue","Black","Frank Castle",null,"Queens, New York","good","Former United States Marine turned professional vigilante"),
    (531,"Purple Man","Male","Human","Purple","Purple","Zebediah Killgrave",null,"-","bad","Professional criminal, Megalomaniac, Former spy"),
    (532,"Pyro","Male",null,"Blue","Blond","St. John Allerdyce",null,"Sydney, Australia","bad","Former government agent, terrorist, bodyguard, novelist, journalist"),
    (533,"Q","Male","God / Eternal","-","-","Q",null,"-","-","-"),
    (535,"Question","Male","Human","Blue","Blond","Charles Victor Szasz",null,"-","good","Former Television Investigative Journalist"),
    (536,"Quicksilver","Male","Mutant","Blue","Silver","Pietro Django Maximoff",null,"Wundagore Mountain, Transia (in Eastern Europe)","good","(current) Adventurer, (former) Terrorist, officer of the Inhumans militia, United States government operative"),
    (537,"Quill","Male",null,"Brown","Brown","Maxwell Jordan",null,"-","good","-"),
    (538,"Ra's Al Ghul","Male","Human","Green","Grey","Ra's Al Ghul",null,"Egypt","bad","Eco Terrorist, Businessman, Cult Leader"),
    (539,"Rachel Pirzad","Female","Alpha","-","-",null,null,"-","good","-"),
    (540,"Rambo","Male","Human","Brown","Black","John Rambo",null,"Bowie, Arizona","good","United States Army soldier (former)"),
    (541,"Raphael","Male","Mutant","-","No Hair",null,null,"-","good","-"),
    (542,"Raven","Female","Human","Indigo","Black","Rachel Roth",null,"Azarath","neutral","Adventurer, high school student"),
    (543,"Ray","Male","Human","Green","Red","Ray Terrill",null,"-","good","Freelance Computer Programmer and Software Designer"),
    (545,"Red Arrow","Male","Human","Green","Red","Roy Harper",null,"-","good","Adventurer; intelligence agent; musician"),
    (546,"Red Hood","Male","Human","Blue","Black","Jason Todd",null,"-","neutral","Mercenary, Vigilante"),
    (547,"Red Hulk","Male","Human / Radiation","Yellow","Black","Thaddeus E. Ross",null,"-","neutral","Lieutenant general in US Air Force"),
    (548,"Red Mist","Male",null,"-","-","Chris Genovese",null,"-","bad","-"),
    (549,"Red Robin","Male","Human","Blue","Black","Tim Drake",null,"Gotham City","good","-"),
    (550,"Red Skull","Male",null,"Blue","No Hair","Johann Shmidt",null,"An unidentified village in Germany","bad","-"),
    (551,"Red Tornado","Male","Android","Green","No Hair","John Smith",null,"-","good","-"),
    (555,"Rey","Female","Human","Hazel","Brown",null,null,"Jakku","good","Scavenger"),
    (556,"Rhino","Male","Human / Radiation","Brown","Brown","Aleksei Mikhailovich Sytsevich",null,"-","bad","Professional Criminal ,Henchman of the Russian Mafia"),
    (557,"Rick Flag","Male",null,"Blue","Brown","Richard Rogers Flag",null,"-","bad","Government Agent, Covert Ops field Commander"),
    (558,"Riddler","Male",null,"-","-","Edward Nigma",null,"-","bad","-"),
    (559,"Rip Hunter","Male","Human","Blue","Blond","Richard Hunter",null,"-","good","-"),
    (561,"Robin","Male","Human","Blue","Black","Dick Grayson",null,"-","good","-"),
    (562,"Robin II","Male","Human","Blue","Red","Jason Todd",null,"-","good","-"),
    (563,"Robin III","Male","Human","Blue","Black","Tim Drake",null,"-","good","High School Student"),
    (564,"Robin V","Male","Human","Blue","Black","Damian Wayne",null,"-","good","-"),
    (565,"Robin VI","Female","Human","Green","Red","Carrie Kelley",null,"Gotham City","neutral","-"),
    (566,"Rocket Raccoon","Male","Animal","Brown","Brown","Rocket Raccoon",null,"-","good","Law enforcement officer, security guard, member of the Guardians of the Galaxy"),
    (567,"Rogue","Female",null,"Green","Brown / White","Anna Marie",null,"Caldecott County, Mississippi","good","Adventurer, former mechanic, waitress, terrorist"),
    (568,"Ronin","Male","Human","Blue","Blond","Clint Barton",null,"Waverly, Iowa","good","Outlaw adventurer, revolutionary; former professional super hero, fugitive, unnoficial S.H.I.E.L.D. operative, federal inmate, CTE security chief, ranch hand, archery tutor, carnival performer, roustabout, butcher shop worker"),
    (569,"Rorschach","Male","Human","Blue","Red","Walter Joseph Kovacs",null,"-","good","Vigilante, former garment worker"),
    (570,"Sabretooth","Male","Mutant","Amber","Blond","Victor Creed",null,"-","bad","mercenary, professional criminal, assassin, serial killer"),
    (571,"Sage","Female",null,"Blue","Black","Tessa",null,"Place of birth unknown","good","Former Soldier"),
    (572,"Sandman","Male","Human","Brown","Brown","William Baker",null,"Queens, New York","neutral","Professional Criminal"),
    (573,"Sasquatch","Male",null,"Red","Orange","Walter Langkowski",null,"Edmonton, Alberta, Canada","good","Adventurer, bio-physicist, government operative; former college lecturer, professional football player"),
    (574,"Sauron","Male","Maiar","-","-","Sauron",null,"-","bad","-"),
    (575,"Savage Dragon","Male",null,"-","-","Kurr",null,"-","good","-"),
    (576,"Scarecrow","Male","Human","Blue","Brown","Jonathan Crane",null,"-","bad","Special Professional Criminal"),
    (577,"Scarlet Spider","Male","Human","Blue","Blond","Benjamin Reilly",null,"Place of birth unknown","good","Crime-fighter"),
    (578,"Scarlet Spider II","Male","Clone","Brown","Brown","Kaine Parker",null,"-","good","Fugitive"),
    (579,"Scarlet Witch","Female","Mutant","Blue","Brown","Wanda Maximoff",null,"Wundagore Mountain, Transia","bad","Adventurer; formerly witchcraft tutor, housewife, terrorist"),
    (580,"Scorpia","Female",null,"Green","Red","Elaine Coll",null,"-","bad","Professional criminal"),
    (581,"Scorpion","Male","Human","Brown","Brown","MacDonald Gargan",null,"-","bad","U.S. government agent; former professional criminal, assassin, private detective"),
    (582,"Sebastian Shaw","Male","Mutant","-","-","Sebastian Hiram Shaw",null,"-","bad","-"),
    (583,"Sentry","Male","Mutant","Blue","Blond","Robert Reynolds",null,"-","neutral","-"),
    (584,"Shadow King","-",null,"Red","-","Amahl Farouk",null,"-","good","-"),
    (585,"Shadow Lass","Female","Talokite","Black","Black","Tasmia Mallor",null,"Talok VIII","good","-"),
    (586,"Shadowcat","Female","Mutant","Hazel","Brown","Kitty Pryde",null,"Deerfield, Illinois","good","Teacher, Adventurer, former student"),
    (587,"Shang-Chi","Male","Human","Brown","Black","Shang-Chi",null,"-","good","-"),
    (588,"Shatterstar","Male",null,"Brown","Red","Gaveedra Seven",null,"Mojoworld","good","Warrior"),
    (589,"She-Hulk","Female","Human","Green","Green","Jennifer Walters",null,"Los Angeles, California","good","Lawyer, Magistra of the Living Tribunal"),
    (590,"She-Thing","Female","Human / Radiation","Blue","No Hair","Sharon Ventura",null,"-","good","Prisoner, former adventurer, wrestler, stuntwoman, scuba diver, motorcycle performer"),
    (591,"Shocker","Male","Human","Brown","Brown","Herman Schultz",null,"-","bad","Professional thief, hired assassin"),
    (592,"Shriek","Female",null,"Yellow / Blue","Black","Frances Louise Barrison",null,"-","good","Former partner of Carnage, Carrion (Malcolm McBride), Demogoblin and Doppelganger). Before she became Shriek, she was a rock band groupie and drug dealer."),
    (594,"Sif","Female","Asgardian","Blue","Black","Sif",null,"-","good","-"),
    (595,"Silk","Female","Human","Brown","Black","Cindy Moon",null,"-","good","Vigilante, intern at Fact Channel News, adventurer; former student"),
    (598,"Silver Surfer","Male","Alien","White","No Hair","Norrin Radd",null,"Zenn-La","good","Adventurer, formerly Galactus' Herald"),
    (599,"Silverclaw","Female",null,"Brown","Black","Maria de Guadalupe Santiago",null,"The village of Kamekeri, Costa Verde","good","University student, adventurer"),
    (600,"Simon Baz","Male","Human","Bown","Black","Simoon Baz",null,"Dearborn, Michigan","good","-"),
    (601,"Sinestro","Male","Korugaran","Black","Black","Thaal Sinestro",null,"Korugar City, Korugar","neutral","-"),
    (602,"Siren","Female","Atlantean","Blue","Purple","Hila",null,"-","bad","-"),
    (604,"Siryn","Female",null,"Blue","Strawberry Blond","Theresa Rourke Cassidy",null,"Cassidy Keep, County Mayo, Ireland","bad","(current) Adventurer (former) Professional Criminal"),
    (605,"Skaar","Male",null,"Green","Black",null,null,"Sakaar","good","Warrior"),
    (607,"Snowbird","Female",null,"White","Blond","Narya",null,"Near Resolute Bay, Northwest Territories, Canada","good","Goddess, adventurer, former records officer"),
    (608,"Sobek","Male",null,"White","No Hair","Yurrd the Unknown",null,"Nile River; Bioengineered at Oolong Island","good","-"),
    (609,"Solomon Grundy","Male","Zombie","Black","White","Cyrus Gold",null,"Gotham City","bad","-"),
    (610,"Songbird","Female",null,"Green","Red / White","Melissa Joan Gold",null,"Shoshoni, Wyoming","good","Adventurer; former criminal and wrestler"),
    (611,"Space Ghost","Male","Human","-","-","Thaddeus Bach",null,"-","good","-"),
    (612,"Spawn","Male","Demon","Brown","Black","Al Simmons",null,"Detroit, Michigan (8th level of Hell after rebirth)","good","-"),
    (613,"Spectre","Male","God / Eternal","White","No Hair","Aztar",null,"-","good","-"),
    (615,"Speedy","Female","Human","Green","Brown","Thea Queen",null,"Starling City","good","Nightclub Owner"),
    (618,"Spider-Girl","Female","Human","Blue","Brown","May 'Mayday' Parker",null,"New York City, New York","good","-"),
    (619,"Spider-Gwen","Female","Human","Blue","Blond","Gwen Stacy",null,"-","good","-"),
    (620,"Spider-Man","Male","Human","Hazel","Brown","Peter Parker",null,"New York, New York","good","Freelance photographer, teacher"),
    (623,"Spider-Woman","Female","Human","Green","Black","Jessica Drew",null,"London, England","good","Form agent of HYDRA, former bounty hunter, private investigator, adventurer"),
    (625,"Spider-Woman III","Female",null,"Brown","Brown","Martha Franklin",null,"Rochester, New York","good","-"),
    (627,"Spock","Male","Human-Vulcan","Brown","Black","S'chn T'gai Spock",null,"-","good","-"),
    (628,"Spyke","Male","Mutant","Brown","Blond","Evan Daniels",null,"-","good","-"),
    (630,"Star-Lord","Male","Human-Spartoi","Blue","Blond","Peter Jason Quill",null,"-","good","Adventurer; Royal Prince of Spartax"),
    (631,"Stardust","Male",null,"-","-",null,null,"-","good","Herald of Galactus"),
    (632,"Starfire","Female","Tamaranean","Green","Auburn","Koriand'r",null,"Tamaran","good","Model"),
    (633,"Stargirl","Female","Human","Blue","Blond","Courtney Whitmore",null,"-","good","-"),
    (634,"Static","Male","Mutant","Brown","Black","Virgil Hawkins",null,"Paris Island, Dakota City","good","Student"),
    (635,"Steel","Male",null,"Brown","No Hair","John Henry Irons",null,"Washington, D.C.","good","Weapons designer, former steelworker"),
    (636,"Stephanie Powell","Female",null,"-","Blond","Stephanie Powell",null,"-","good","Executive Vice President of Research at Global Tech"),
    (637,"Steppenwolf","Male","New God","Red","Black",null,null,"-","bad","-"),
    (638,"Storm","Female","Mutant","Blue","White","Ororo Munroe",null,"New York, New York","good","Adventurer"),
    (639,"Stormtrooper","Male","Human","-","-",null,null,"-","bad","-"),
    (640,"Sunspot","Male","Mutant","brown","black","Roberto DaCosta",null,"Rio de Janeiro, Brazil","good","Adventurer, businessman"),
    (641,"Superboy","Male",null,"Blue","Black","Kon-El / Conner Kent",null,"Project Cadmus cloning facility","good","-"),
    (642,"Superboy-Prime","Male","Kryptonian","Blue","Black / Blue","Kal-El",null,"Krypton (Earth-Prime)","bad","-"),
    (643,"Supergirl","Female","Kryptonian","Blue","Blond","Kara Zor-El",null,"Argo City, Krypton","good","Intern, Adventurer, Student, Crime-Fighter"),
    (644,"Superman","Male","Kryptonian","Blue","Black","Clark Kent",null,"Krypton","good","Reporter for the Daily Planet and novelist"),
    (645,"Swamp Thing","Male","God / Eternal","Red","No Hair","Alec Holland",null,"-","bad","Planet Elemental, former Biochemist"),
    (646,"Swarm","Male","Mutant","Yellow","No Hair","Fritz von Meyer",null,"-","bad","Ph.D. in toxicology & entomology"),
    (647,"Sylar","Male",null,"-","-","Gabriel Gray",null,"-","bad","Timepiece restorer"),
    (648,"Synch","Male",null,"Brown","Black","Everett Thomas",null,"-","good","Student"),
    (649,"T-1000","Male","Android","-","-","Cyberdyne Systems Series 1000 Terminator",null,"-","bad","-"),
    (650,"T-800","Male","Cyborg","Red","-","Cyberdyne Systems Series 800 Terminator Model 101",null,"-","bad","Assassin"),
    (651,"T-850","Male","Cyborg","Red","-","Cyberdyne Systems Series 850 Terminator",null,"-","bad","Assassin"),
    (652,"T-X","Female","Cyborg","-","-","Cyberdyne Systems Series X Terminator",null,"-","bad","Assassin / Genesis Overseer"),
    (653,"Taskmaster","Male","Human","Brown","Brown","Tony Masters",null,"-","bad","Sheriff, Assassin, Mercenary; formerly Military Trainer, Combat Instructor, Head of Initiative training camp"),
    (654,"Tempest","Female",null,"Brown","Black","Angel Salvadore Bohusk",null,"-","good","-"),
    (655,"Thanos","Male","Eternal","Red","No Hair","Thanos",null,"Titan","bad","Conqueror, worshiper of Death"),
    (656,"The Cape","Male",null,"-","-","Vince Faraday",null,"-","good","-"),
    (657,"The Comedian","Male","Human","Brown","Black","Edward Morgen Blake",null,"-","neutral","Former Adventurer; Government Agent"),
    (658,"Thing","Male","Human / Radiation","Blue","No Hair","Ben Grimm",null,"New York City, New York","good","Adventurer, former Air Force test pilot"),
    (659,"Thor","Male","Asgardian","Blue","Blond","Thor Odinson",null,"Asgard","good","King of Asgard; formerly EMS Technician; Physician"),
    (660,"Thor Girl","Female","Asgardian","Blue","Blond","Tarene",null,"-","good","-"),
    (661,"Thunderbird","Male",null,"Brown","Black","John Proudstar",null,"Camp Verde, Arizona","good","Former adventurer, student, Marine"),
    (664,"Thunderstrike","Male",null,"Blue","Blond","Eric Kevin Masterson",null,"-","good","(as Thunderstrike) Adventurer, crimefighter, (as Masterson) Architect"),
    (665,"Thundra","Female",null,"Green","Red","Thundra",null,"-","good","Ruler, warrior"),
    (666,"Tiger Shark","Male","Human","Grey","No Hair","Todd Arliss",null,"Pasadena, California","bad","-"),
    (667,"Tigra","Female",null,"Green","Auburn","Greer Grant Nelson",null,"Presumably Chicago Illinois USA","good","Laboratory assistant, model, adventurer, NYC police"),
    (668,"Tinkerer","Male",null,"Brown","White","Phineas Mason",null,"-","bad","Inventor and technician serving the underworld"),
    (670,"Toad","Male","Mutant","Black","Brown","Mortimer Toynbee",null,"York, England","neutral","Former criminal"),
    (671,"Toxin","Male","Symbiote","Blue","Brown","Patrick Mulligan",null,"New York City","good","Police officer"),
    (672,"Toxin","Male","Symbiote","Black","Blond","Eddie Brock",null,"San Francisco, California","good","Vigilante; former symbiote hunter, shelter attendant, government operative, journalist for the Daily Globe"),
    (676,"Triplicate Girl","Female",null,"Purple","Brown","Luornu Durgo",null,"-","good","-"),
    (677,"Triton","Male","Inhuman","Green","No Hair","Triton",null,"Island of Attilan, Atlantic Ocean","good","-"),
    (678,"Two-Face","Male",null,"-","-","Harvey Dent",null,"-","bad","Reformed criminal; former district attorney"),
    (679,"Ultragirl","Female",null,"Blue","Blond","Tsu-Zana",null,"-","good","Model"),
    (680,"Ultron","Male","Android","Red","-","Ultron",null,"Created in Cresskill, New Jersey","bad","Mass murderer, scientist, would-be world conqueror, ruler of Phalanx"),
    (681,"Utgard-Loki","Male","Frost Giant","Blue","White",null,null,"Jotunheim","bad","Monarch"),
    (685,"Vanisher","Male",null,"Green","No Hair",null,null,"Boston, Massachusetts","bad","Professional criminal, former subversive"),
    (686,"Vegeta","Male","Saiyan","-","Black","Vegeta",null,"-","bad","-"),
    (687,"Venom","Male","Symbiote","Blue","Strawberry Blond","Eddie Brock",null,"New York, New York","bad","Vigilante; former journalist for the Daily Globe, government operative"),
    (688,"Venom II","Male",null,"Brown","Black","Angelo Fortunato",null,"-","bad","-"),
    (689,"Venom III","Male","Symbiote","Brown","Brown","MacDonald Gargan",null,"-","bad","Government operative; former professional criminal, private eye"),
    (690,"Venompool","Male","Symbiote","-","-","Wade Wilson",null,"-","-","Conqueror; Adventurer"),
    (692,"Vibe","Male","Human","Brown","Black","Cisco Ramon",null,"-","good","-"),
    (693,"Vindicator","Female","Human","Green","Red","Heather Hudson",null,"Calgary, Alberta, Canada","good","former secretary, researcher"),
    (696,"Violet Parr","Female","Human","Violet","Black","Violet Parr",null,"-","good","-"),
    (697,"Vision","Male","Android","Gold","No Hair","Vision",null,"-","good","-"),
    (699,"Vixen","Female","Human","Amber","Black","Mari McCabe",null,"Zambesi","good","Former Model"),
    (701,"Vulture","Male","Human","Brown","No Hair","Adrian Toomes",null,"Staten Island, New York City","bad","Professional criminal; formerly electronics engineer"),
    (702,"Walrus","Male","Human","Blue","Black","Hubert Carpent",null,"Brooklyn, New York","bad","Cab driver"),
    (703,"War Machine","Male","Human","Brown","Brown","James Rupert Rhodes",null,"Philadelphia, Pennsylvania","good","Initiative instructor, adventurer, government agent; formerly: Sentinel Squad O*N*E combat instructor, soldier, pilot"),
    (705,"Warlock","Male",null,"Red","Blond","Adam Warlock",null,"The Beehive, Shard Island, Atlantic Ocean","good","Avenger, savior of worlds"),
    (706,"Warp","Male",null,"Brown","Black","Emil LaSalle",null,"-","bad","-"),
    (707,"Warpath","Male","Mutant","Brown","Black","James Proudstar",null,"Camp Verde, Arizona","good","Adventurer"),
    (708,"Wasp","Female","Human","Blue","Auburn","Janet Van Dyne",null,"Cresskill, New Jersey","good","Adventurer, fashion designer, independently wealthy socialite"),
    (709,"Watcher","Male",null,"-","-","Uatu",null,"-","good","-"),
    (711,"White Canary","Female","Human","Brown","Black",null,null,"-","bad","-"),
    (713,"Wildfire","Male",null,"-","-","Drake Burroughs",null,"-","good","-"),
    (714,"Winter Soldier","Male","Human","Brown","Brown","Bucky Barnes",null,"-","good","Adventurer; former SHIELD operative, Assassin (See Note under \"Winter Soldier\" article), Army Mascot, Student"),
    (716,"Wolfsbane","Female",null,"Green","Auburn","Rahne Sinclair",null,"Somewhere in Ross and Cromarty, Scotland","good","Teacher"),
    (717,"Wolverine","Male","Mutant","Blue","Black","Logan",null,"Alberta, Canada","good","Adventurer, instructor, former bartender, bouncer, spy, government operative, mercenary, soldier, sailor, miner"),
    (718,"Wonder Girl","Female","Demi-God","Blue","Blond","Cassandra Elizabeth Sandsmark",null,"-","good","-"),
    (719,"Wonder Man","Male",null,"Red","Black","Simon Williams",null,"Paterson, New Jersey","good","Former industrialist, now stuntman, actor, adventurer"),
    (720,"Wonder Woman","Female","Amazon","Blue","Black","Diana Prince",null,"Themyscira","good","Adventurer, Emissary to the world of Man, Protector of Paradise Island; former Goddess of Truth"),
    (722,"Wyatt Wingfoot","Male",null,"Brown","Black","Wyatt Wingfoot",null,"Keewazi Reservation, Oklahoma","good","Occasional adventurer"),
    (723,"X-23","Female","Mutant / Clone","Green","Black","Laura Kinney",null,"The Facility, location unrevealed","good","Adventurer, Student, former; Assassin, Prostitute"),
    (724,"X-Man","Male",null,"Blue","Brown","Nate Grey",null,"American Northeast of Earth-295","good","Former shaman, adventurer, freedom fighter"),
    (726,"Yellowjacket","Male","Human","Blue","Blond","Hank Pym",null,"Elmsford, New York","good","Adventurer, Biochemist, former manager of Avengers Compound"),
    (727,"Yellowjacket II","Female","Human","Blue","Strawberry Blond","Rita DeMara",null,"-","good","Adventurer; former criminal, electronics engineer"),
    (728,"Ymir","Male","Frost Giant","White","No Hair","Ymir",null,"Niffleheim","good","-"),
    (729,"Yoda","Male","Yoda's species","Brown","White","Yoda",null,"-","good","-"),
    (730,"Zatanna","Female","Human","Blue","Black","Zatanna Zatara",null,"-","good","-"),
    (731,"Zoom","Male",null,"Red","Brown","Hunter Zolomon",null,"-","bad","-")
ON DUPLICATE KEY UPDATE name=VALUES(name), gender=VALUES(gender), race=VALUES(race), eye_colour=VALUES(eye_colour), hair_colour=VALUES(hair_colour), full_name=VALUES(full_name), alter_egos=VALUES(alter_egos), place_of_birth=VALUES(place_of_birth), alignment=VALUES(alignment), occupation=VALUES(occupation);